[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "esp32robot"
version = "0.0.1"
description = "AI-controlled autonomous ESP32 robot car"
authors = [
  { name = "Pedro Braga" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"
dependencies = [
    "black>=25.11.0",
    "flake8>=7.3.0",
    "flask>=3.1.2",
    "gymnasium>=1.2.2",
    "ipython>=8.37.0",
    "isort>=7.0.0",
    "jupyterlab>=4.5.0",
    "loguru>=0.7.3",
    "matplotlib>=3.10.7",
    "mlflow>=3.6.0",
    "notebook>=7.5.0",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "optuna>=4.6.0",
    "pandas>=2.3.3",
    "perlin-noise>=1.14",
    "pillow>=12.0.0",
    "pip>=25.3",
    "pybullet>=3.2.7",
    "pygame>=2.6.1",
    "pytest>=9.0.1",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "timm>=1.0.22",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
    "transformers>=4.57.3",
    "typer>=0.20.0",
]

[tool.black]
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
)/
'''

[tool.isort]
profile = "black"
known_first_party = ["esp32robot"]
force_sort_within_sections = true


