# ==========================================
# CONFIGURAÇÃO DE PRÉ-TREINO (MineRL)
# ==========================================

dataset:
  train_path: "datasets/carracing_human/train"
  test_path: "datasets/carracing_human/test"
  img_size: 96
  # Mapeamento de ações MineRL -> Robô (0:Stop, 1:Fwd, 2:Back, 3:Left, 4:Right)
  # O código usará heurísticas (camera_x, forward, etc) para decidir
  action_mapping: true
  max_videos: 5
model:
  input_shape: [3, 96, 96]
  n_actions: 5        # Stop, Fwd, Back, Left, Right
  n_categories: 512    # Tamanho do codebook latente
  hidden_size: 1024
  ch_channels: 64
  
training:
  experiment_name: "carracing_pretrain_v1"
  output_dir: "models/"
  model_name: "visual_world_model_carracing"
  patience: 100
  
  epochs: 1000
  batch_size: 64      # Ajuste conforme sua VRAM (32 ou 64 é seguro pra 64x64)
  learning_rate: 0.001
  save_every_step: 1000
  
  # Pesos da Loss
  beta_rec: 1.0      # Peso da Reconstrução (Visão)
  beta_pred: 0.2      # Peso da Predição (Física)
  beta_inverse: 1

  beta_entropy: 30